---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sonicrem/public_html/
    - /bin/cp -R survey/build/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - export BACKENDPATH=/home/sonicrem/
    - /bin/cp -R survey-backend $BACKENDPATH
