---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sonicrem/repositories/Sonic-Remedies/
    - /survey -R public $DEPLOYPATH
    - /survey -R src $DEPLOYPATH
    - /survey/.npmrc $DEPLOYPATH
    - /survey/package.json $DEPLOYPATH
